version: "3.8"
services:
  stasis-pdf:
    image: "xcommodore64/stasis:latest"
    container_name: stasis-pdf
    environment:
      NODE_ENV: production
      TEMPLATES_DIR: /app/templates
    ports:
      - "127.0.0.1:7070:7070"
    user: root
    command: 'bash -c "chmod -R 777 /app/templates && chown -R pwuser:pwuser /app/templates && su pwuser -c ''node /app/dist/index.js''"'
    volumes:
      - "stasis_pdf_templates:/app/templates:rw"
    networks:
      - intercom
volumes:
  stasis_pdf_templates: null
networks:
  intercom: null
