version: "3.8"

services:
  pdf-generation-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stasis
    environment:
      NODE_ENV: production
    ports:
      - 7070:7070
    volumes:
      - pdf_templates:/app/src/templates # Use named volume for template persistence

volumes:
  pdf_templates:
    # Named volume for templates that persists across container recreations
